-- Human-readable numbers for requests and issues.
--
-- Generated by the database from sequences, so two people submitting at the
-- same moment can never be handed the same number. An application that
-- counted existing rows and added one would race.
--
-- Callers that supply their own number (seed data, tests, carry-forward's
-- "-CF" suffix) still can; the default applies only when the column is omitted.

CREATE SEQUENCE IF NOT EXISTS request_number_seq;
CREATE SEQUENCE IF NOT EXISTS issue_number_seq;

GRANT USAGE, SELECT ON SEQUENCE request_number_seq TO app_user;
GRANT USAGE, SELECT ON SEQUENCE issue_number_seq   TO app_user;

-- lpad() truncates a value longer than the target width, so a plain
-- lpad(n, 4) would turn request 12345 into '1234' and collide with an
-- earlier number. The width grows with the value instead.
CREATE OR REPLACE FUNCTION fn_pad_number(p_n BIGINT, p_width INT)
RETURNS TEXT AS $$
    SELECT lpad(p_n::TEXT, GREATEST(p_width, length(p_n::TEXT)), '0');
$$ LANGUAGE sql IMMUTABLE;

-- REQ-2026-0001
CREATE OR REPLACE FUNCTION fn_next_request_number()
RETURNS TEXT AS $$
    SELECT 'REQ-' || to_char(NOW(), 'YYYY') || '-' || fn_pad_number(nextval('request_number_seq'), 4);
$$ LANGUAGE sql VOLATILE;

-- ISS-0001
CREATE OR REPLACE FUNCTION fn_next_issue_number()
RETURNS TEXT AS $$
    SELECT 'ISS-' || fn_pad_number(nextval('issue_number_seq'), 4);
$$ LANGUAGE sql VOLATILE;

ALTER TABLE requests ALTER COLUMN request_number SET DEFAULT fn_next_request_number();
ALTER TABLE issues   ALTER COLUMN issue_number   SET DEFAULT fn_next_issue_number();
