-- Notifications, generated by the database when a request or issue changes.
--
-- WHY TRIGGERS, AND WHY SECURITY DEFINER
-- Notifying someone means inserting a row that belongs to THEM. RLS only lets
-- a user insert their own notifications, so a requester submitting a request
-- could never notify the approvers it now waits on. These trigger functions
-- run as their owner to write those rows. They cannot be called directly —
-- a trigger function only runs when its trigger fires — so there is no way
-- to use them to send arbitrary notifications.
--
-- Recipients come from roles and stage staffing, never hard-coded addresses,
-- as the design document requires. Only in-app notifications are created;
-- delivering email is left to a worker that reads PENDING EMAIL rows.

-- ---------------------------------------------------------------------------
-- Requests
-- ---------------------------------------------------------------------------
--   enters a review stage   -> every approver staffed at that stage
--   escalated upward        -> additionally the requester, so they know
--   approved / partially approved / rejected / carried forward -> the requester

CREATE OR REPLACE FUNCTION fn_notify_request_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_stage_name TEXT;
    v_label      TEXT := lower(replace(NEW.current_status::TEXT, '_', ' '));
BEGIN
    IF left(NEW.current_status::TEXT, 6) = 'UNDER_' THEN
        SELECT name INTO v_stage_name
        FROM workflow_stages WHERE stage_id = NEW.current_stage_id;

        INSERT INTO notifications (user_id, request_id, subject, body)
        SELECT sa.user_id, NEW.request_id,
               'Request ' || NEW.request_number || ' awaits your review',
               NEW.title || ' is now with ' || v_stage_name || '.'
        FROM stage_approvers sa
        WHERE sa.stage_id = NEW.current_stage_id;

        IF left(OLD.current_status::TEXT, 6) = 'UNDER_' THEN
            INSERT INTO notifications (user_id, request_id, subject, body)
            VALUES (NEW.raised_by, NEW.request_id,
                    'Request ' || NEW.request_number || ' escalated',
                    'Forwarded to ' || v_stage_name || ' for review.');
        END IF;

    ELSIF NEW.current_status IN ('APPROVED','PARTIALLY_APPROVED','REJECTED','CARRIED_FORWARD') THEN
        INSERT INTO notifications (user_id, request_id, subject, body)
        VALUES (NEW.raised_by, NEW.request_id,
                'Request ' || NEW.request_number || ' ' || v_label,
                CASE
                    WHEN NEW.current_status IN ('APPROVED','PARTIALLY_APPROVED')
                        THEN 'Sanctioned amount: ' || COALESCE(NEW.sanctioned_amount, 0)::TEXT
                             || ' of ' || NEW.tentative_total_cost::TEXT || ' requested.'
                    ELSE NEW.title
                END);
    END IF;

    RETURN NULL;
END;
$$;

CREATE TRIGGER requests_notify_status
    AFTER UPDATE OF current_status ON requests
    FOR EACH ROW
    WHEN (OLD.current_status IS DISTINCT FROM NEW.current_status)
    EXECUTE FUNCTION fn_notify_request_status();

-- ---------------------------------------------------------------------------
-- Non-financial issues
-- ---------------------------------------------------------------------------
--   raised              -> every Principal
--   status changes      -> the raiser
--   assigned            -> the new assignee
--   escalated to someone -> that person

CREATE OR REPLACE FUNCTION fn_notify_issue()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO notifications (user_id, issue_id, subject, body)
        SELECT ur.user_id, NEW.issue_id,
               'New issue ' || NEW.issue_number, NEW.title
        FROM user_roles ur
        JOIN roles r ON r.role_id = ur.role_id
        WHERE r.code = 'PRINCIPAL'
          AND ur.user_id <> NEW.raised_by;
        RETURN NULL;
    END IF;

    IF NEW.status IS DISTINCT FROM OLD.status THEN
        INSERT INTO notifications (user_id, issue_id, subject, body)
        VALUES (NEW.raised_by, NEW.issue_id,
                'Issue ' || NEW.issue_number || ' is now '
                    || lower(replace(NEW.status::TEXT, '_', ' ')),
                NEW.title);
    END IF;

    IF NEW.assigned_to IS NOT NULL
       AND NEW.assigned_to IS DISTINCT FROM OLD.assigned_to THEN
        INSERT INTO notifications (user_id, issue_id, subject, body)
        VALUES (NEW.assigned_to, NEW.issue_id,
                'Issue ' || NEW.issue_number || ' assigned to you', NEW.title);
    END IF;

    IF NEW.escalated_to IS NOT NULL
       AND NEW.escalated_to IS DISTINCT FROM OLD.escalated_to THEN
        INSERT INTO notifications (user_id, issue_id, subject, body)
        VALUES (NEW.escalated_to, NEW.issue_id,
                'Issue ' || NEW.issue_number || ' escalated to you', NEW.title);
    END IF;

    RETURN NULL;
END;
$$;

CREATE TRIGGER issues_notify_insert
    AFTER INSERT ON issues
    FOR EACH ROW
    EXECUTE FUNCTION fn_notify_issue();

CREATE TRIGGER issues_notify_update
    AFTER UPDATE OF status, assigned_to, escalated_to ON issues
    FOR EACH ROW
    EXECUTE FUNCTION fn_notify_issue();
