-- ===========================================================================
-- DEVELOPMENT SEED ONLY — DO NOT LOAD ON THE COLLEGE SERVER
-- ===========================================================================
-- Creates one account per role plus the stage_approvers wiring, so the
-- approval workflow can actually be exercised end to end locally.
--
-- Every account below shares the same throwaway password:
--
--     ChangeMe#2026
--
-- The hash is generated by pgcrypto at seed time, so nothing secret is stored
-- in this file. These accounts are still real logins — before deploying,
-- either skip this file entirely or reset every password.
-- ===========================================================================

INSERT INTO users (email, full_name, password_hash, department_id) VALUES
    ('head.cs@spcollege.edu',    'Dr. A. Deshpande (Head, CS)',   crypt('ChangeMe#2026', gen_salt('bf', 12)), (SELECT department_id FROM departments WHERE code = 'CS')),
    ('head.chem@spcollege.edu',  'Dr. B. Chemist (Head, Chemistry)', crypt('ChangeMe#2026', gen_salt('bf', 12)), (SELECT department_id FROM departments WHERE code = 'CHEM')),
    ('incharge@spcollege.edu',   'S. Kulkarni (Activity In-charge)', crypt('ChangeMe#2026', gen_salt('bf', 12)), (SELECT department_id FROM departments WHERE code = 'CS')),
    ('pc1@spcollege.edu',        'R. Joshi (Purchase Committee)', crypt('ChangeMe#2026', gen_salt('bf', 12)), NULL),
    ('pc2@spcollege.edu',        'M. Patil (Purchase Committee)', crypt('ChangeMe#2026', gen_salt('bf', 12)), NULL),
    ('principal@spcollege.edu',  'Dr. V. Rane (Principal)',       crypt('ChangeMe#2026', gen_salt('bf', 12)), NULL),
    ('cdc.grant@spcollege.edu',  'P. Shinde (CDC Grant)',         crypt('ChangeMe#2026', gen_salt('bf', 12)), NULL),
    ('cdc.nongrant@spcollege.edu','N. Gokhale (CDC Non-Grant)',   crypt('ChangeMe#2026', gen_salt('bf', 12)), NULL),
    ('chairman@spcollege.edu',   'Shri. K. Bhave (Chairman)',     crypt('ChangeMe#2026', gen_salt('bf', 12)), NULL),
    ('vp@spcollege.edu',         'Smt. L. Karve (Vice President)',crypt('ChangeMe#2026', gen_salt('bf', 12)), NULL),
    ('clerk@spcollege.edu',      'D. Sawant (Clerk)',             crypt('ChangeMe#2026', gen_salt('bf', 12)), NULL),
    ('admin@spcollege.edu',      'System Administrator',          crypt('ChangeMe#2026', gen_salt('bf', 12)), NULL)
ON CONFLICT (email) DO UPDATE SET department_id = EXCLUDED.department_id;

-- Role assignments.
INSERT INTO user_roles (user_id, role_id)
SELECT u.user_id, r.role_id
FROM (VALUES
    ('head.cs@spcollege.edu',      'HEAD'),
    ('head.chem@spcollege.edu',    'HEAD'),
    ('incharge@spcollege.edu',     'ACTIVITY_INCHARGE'),
    ('pc1@spcollege.edu',          'PURCHASE_COMMITTEE'),
    ('pc2@spcollege.edu',          'PURCHASE_COMMITTEE'),
    ('principal@spcollege.edu',    'PRINCIPAL'),
    ('cdc.grant@spcollege.edu',    'CDC_GRANT_MEMBER'),
    ('cdc.grant@spcollege.edu',    'CDC_MEMBER'),
    ('cdc.nongrant@spcollege.edu', 'CDC_NON_GRANT_MEMBER'),
    ('cdc.nongrant@spcollege.edu', 'CDC_MEMBER'),
    ('chairman@spcollege.edu',     'CHAIRMAN'),
    ('vp@spcollege.edu',           'VICE_PRESIDENT'),
    ('admin@spcollege.edu',        'ADMIN')
) AS v(email, role_code)
JOIN users u ON u.email = v.email
JOIN roles r ON r.code  = v.role_code
ON CONFLICT (user_id, role_id) DO NOTHING;

-- Stage staffing. This is the part that makes fn_record_action work: without
-- rows here, nobody has authority to decide anything at any stage.
INSERT INTO stage_approvers (stage_id, user_id, role_id)
SELECT ws.stage_id, u.user_id, r.role_id
FROM (VALUES
    ('PURCHASE_COMMITTEE', 'pc1@spcollege.edu',          'PURCHASE_COMMITTEE'),
    ('PURCHASE_COMMITTEE', 'pc2@spcollege.edu',          'PURCHASE_COMMITTEE'),
    ('PRINCIPAL',          'principal@spcollege.edu',    'PRINCIPAL'),
    ('CDC',                'cdc.grant@spcollege.edu',    'CDC_GRANT_MEMBER'),
    ('CDC',                'cdc.nongrant@spcollege.edu', 'CDC_NON_GRANT_MEMBER'),
    ('FINAL_AUTHORITY',    'chairman@spcollege.edu',     'CHAIRMAN'),
    ('FINAL_AUTHORITY',    'vp@spcollege.edu',           'VICE_PRESIDENT')
) AS v(stage_code, email, role_code)
JOIN workflow_stages ws ON ws.code = v.stage_code::workflow_stage_code
JOIN users u            ON u.email = v.email
JOIN roles r            ON r.code  = v.role_code
ON CONFLICT (stage_id, user_id) DO NOTHING;
